# This is a config for E2B sandbox template.
# You can use template ID (y4o3rb35l5obxpfx4se1) or template name (ai-nextjs-developer) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("ai-nextjs-developer") # Sync sandbox
# sandbox = await AsyncSandbox.create("ai-nextjs-developer") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ai-nextjs-developer')

team_id = "ef7d85ef-6e45-424d-909e-77f70e1a085e"
dockerfile = "e2b.Dockerfile"
template_name = "ai-nextjs-developer"
template_id = "y4o3rb35l5obxpfx4se1"
